routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}','BlogController@category')->name('category');
Route::get('/blog/post/{slug?}','BlogController@post')->name('post');


Route::group([
    'prefix'=>'admin',
    'namespace'=>'Admin',
    'middleware'=> ['auth']
],function(){
    Route::get('/','DashboardController@dashboard')->name('admin.index');
    Route::resource('/category','CategoryController',['as'=>'admin']);
    Route::resource('/post','PostController',['as'=>'admin']);
});

Route::get('/','BlogController@home')->name('blog.home');

Auth::routes();

app/Post.php
<?php
/**
 * Created by PhpStorm.
 * User: mamyta
 * Date: 20/05/2018
 * Time: 2:09
 */

namespace App;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Illuminate\Support\Str;

class Post extends Eloquent
{
    protected $connection = 'mongodb';

    // mass assigned
    protected $fillable = array(
        'title',
        'slug',
        'category_id',
        'description_short',
        'description',
        'image',
        'pinned',
        'published'
    );

    public function setSlugAttribute($value){
        $this->attributes['slug'] = Str::slug( mb_substr($this->title,0 ,40)."-". \Carbon\Carbon::now()->format('dmyHi'),'-');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function scopeLastPosts($query,$count,$skip=0){
        $posts = Post::where('published','=','1')->orderBy('created_at', 'desc')->skip($skip)->take($count)->get();
        return $posts;
    }

    public function scopeGetPinned($query){
        $post = Post::where('pinned','=','1')->first();
        return $post;
    }

    public function scopeTotalViews($query){
        return Post::sum('view_count');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Post;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.posts.index', [
            'posts' => Post::orderBy('created_at', 'desc')->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.posts.create', [
            'post' => [],
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Post::create($request->all());

        return redirect()->route('admin.post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('admin.posts.edit', [
            'post' => $post,
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $data = $request->except('slug');

        if (!isset($data['pinned'])) {
            $data['pinned'] = 0;
        }
        $post->update($data);
        return redirect()->route('admin.post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('admin.post.index');
    }
}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
        @slot('title') New Post @endslot
        @slot('parent') Home @endslot
        @slot('active') Posts @endslot
        @endcomponent

        <hr />

        <form class="form-horizontal" action="{{route('admin.post.store')}}" method="post">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.posts.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
        @slot('title') Edit Post @endslot
        @slot('parent') Home @endslot
        @slot('active') Posts @endslot
        @endcomponent

        <hr />

        <form class="form-horizontal" action="{{route('admin.post.update',$post)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.posts.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb')
        @slot('title') Posts list @endslot
        @slot('parent') Home @endslot
        @slot('active') Posts @endslot
        @endcomponent
        <table class="table table-striped">
            <thead>
            <th>Title</th>
            <th>Category</th>
            <th>Status</th>
            <th class="text-right"><a href="{{route('admin.post.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"></i> Add Post</a></th>
            </thead>
            <tbody>
            @forelse ($posts as $post)
                <tr>
                    <td>{{$post->title}}</td>
                    <td>{{$post->category->title or ""}}</td>
                    <td>@if ($post->published== 1 ) Published @else Draft @endif</td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Delete?')){return true}else{return false}" action="{{route('admin.post.destroy',$post)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field() }}
                            <a class="btn btn-link" href="{{route('admin.post.edit', $post)}}"><i class="fa fa-edit"></i></a>
                            <button type="submit" class="btn btn-link"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center"><h2>No data</h2></td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>

@endsection