routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}','BlogController@category')->name('category');
Route::get('/blog/post/{slug?}','BlogController@post')->name('post');


Route::group([
    'prefix'=>'admin',
    'namespace'=>'Admin',
    'middleware'=> ['auth']
],function(){
    Route::get('/','DashboardController@dashboard')->name('admin.index');
    Route::resource('/category','CategoryController',['as'=>'admin']);
    Route::resource('/post','PostController',['as'=>'admin']);
});

Route::get('/','BlogController@home')->name('blog.home');

Auth::routes();

app/Category.php
<?php

namespace App;
use Eloquent;
use App\Post;

use Jenssegers\Mongodb\Eloquent\HybridRelations;

use Illuminate\Support\Str;

class Category extends Eloquent
{
    use HybridRelations;

    // mass assigned
    protected $fillable = array(
        'title',
        'slug',
        'parent_id',
        'description'
    );

    protected $connection = 'mysql';

    public function setSlugAttribute($value){
        $this->attributes['slug'] = Str::slug( mb_substr($this->title,0 ,40)."-". \Carbon\Carbon::now()->format('dmyHi'),'-');
    }

    public function posts()
    {
        return Post::where('category_id','=', (string)$this->id)->where('published','=','1')->get();
    }

    public function children(){
        return $this->hasMany(self::class,'parent_id');
    }

    public function scopeLastCategories($query,$count){
        return $query->orderBy('created_at','desc')->take($count)->get();
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.categories.index',[
            'categories' => Category::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create',[
            'category'   => [],
            'categories' => Category::with('children')->where('parent_id','0')->get(),
            'delimiter'  => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());

        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit',[
            'category'   => $category,
            'categories' => Category::with('children')->where('parent_id','0')->get(),
            'delimiter'  => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->except('slug'));
        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.category.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
        @slot('title') New Category @endslot
        @slot('parent') Home @endslot
        @slot('active') Categories @endslot
        @endcomponent

        <hr />

        <form class="form-horizontal" action="{{route('admin.category.store')}}" method="post">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.categories.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
        @slot('title') Edit Category @endslot
        @slot('parent') Home @endslot
        @slot('active') Categories @endslot
        @endcomponent

        <hr />

        <form class="form-horizontal" action="{{route('admin.category.update',$category)}}" method="post">
            <input name="_method" type="hidden" value="PUT">

            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.categories.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
    @component('admin.components.breadcrumb')
        @slot('title') Categories list @endslot
        @slot('parent') Home @endslot
        @slot('active') Categories @endslot
    @endcomponent

    <table class="table table-striped">
        <thead>
        <th>Title</th>
        <th>Description</th>
        <th class="text-right"><a href="{{route('admin.category.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"></i> Add Category</a></th>
        </thead>
        <tbody>
        @forelse ($categories as $category)
            <tr>
                <td>{{$category->title}}</td>
                <td>{{$category->description}}</td>
                <td class="text-right">
                    <form onsubmit="if(confirm('Delete?')){return true}else{return false}" action="{{route('admin.category.destroy',$category)}}" method="post">
                        <input type="hidden" name="_method" value="DELETE">
                        {{ csrf_field() }}
                        <a class="btn btn-link" href="{{route('admin.category.edit', $category)}}"><i class="fa fa-edit"></i></a>
                        <button type="submit" class="btn btn-link"><i class="fa fa-trash-o"></i></button>
                    </form>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="3" class="text-center"><h2>No data</h2></td>
            </tr>
        @endforelse
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3">
                <ul class="pagination pull-right">
                    {{$categories->links()}}
                </ul>
            </td>
        </tr>
        </tfoot>

    </table>
</div>

@endsection